package com.oceanview.resort.dao;

import com.oceanview.resort.model.Reservation;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.time.LocalDate;
import java.sql.SQLException;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Task C: Test-Driven Development (TDD) and Test Automation.
 * This class contains automated test cases to verify the integrity 
 * of database operations within the ReservationDAO.
 */
public class ReservationDAOTest {

    private ReservationDAO reservationDAO;

    /**
     * Initializes the DAO before each test case execution.
     */
    @BeforeEach
    public void setUp() {
        reservationDAO = new ReservationDAO();
    }

    /**
     * Test Case: Verifies that a new reservation can be successfully 
     * inserted into the database and returns a valid ID.
     */
    @Test
    public void testAddReservation() {
        // Create test data (Assumes Guest ID 1 and Room 101 exist in your DB)
        Reservation testRes = new Reservation(1, 101, LocalDate.now(), LocalDate.now().plusDays(2));
        testRes.setStatus("Confirmed");

        try {
            int generatedId = reservationDAO.addReservation(testRes);
            
            // Assertion: The generated ID should be greater than 0
            assertTrue(generatedId > 0, "Reservation ID should be automatically generated by the database.");
            System.out.println("--> [TEST SUCCESS] addReservation passed. Generated ID: " + generatedId);
        } catch (SQLException e) {
            fail("Database connection or query failed: " + e.getMessage());
        }
    }

    /**
     * Test Case: Verifies that a reservation can be retrieved correctly 
     * using its unique ID (Task 3 functionality).
     */
    @Test
    public void testGetReservationById() {
        // ID to test (Adjust based on an existing ID in your test database)
        int testId = 1; 
        
        Reservation retrieved = reservationDAO.getReservationById(testId);
        
        // Assertion: If the ID exists, the object should not be null
        if (retrieved != null) {
            assertEquals(testId, retrieved.getReservationNumber(), "The retrieved ID must match the requested ID.");
            System.out.println("--> [TEST SUCCESS] getReservationById passed for ID: " + testId);
        } else {
            System.out.println("--> [TEST WARNING] getReservationById: No record found for ID " + testId + ". Ensure test data exists.");
        }
    }
}